spring.application.name=jobgraph

spring.neo4j.uri=${COGNODB_URI}
spring.neo4j.authentication.username=${COGNODB_USERNAME}
spring.neo4j.authentication.password=${COGNODB_PASSWORD}

server.port=8081